"""empty message

Revision ID: d3581b86df70
Revises: a36a9157e603
Create Date: 2024-03-15 21:23:55.985313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3581b86df70'
down_revision = 'a36a9157e603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.drop_column('propertytype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertytype', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
